@warning_ignore_start("inferred_declaration")
## GameStateManager FSM 核心与状态转换测试
##
## 使用 GDUnit4 框架。
## 测试覆盖 ADR-0001 和 Story FSM Core & State Transitions 的所有 AC。
# GdUnit generated test suite
# WARN: Generated by GdUnit — do not edit manually.

extends GdUnitTestSuite

## 测试用 GameStateManager 实例
var _manager: GameStateManager


func before_test() -> void:
	_manager = auto_free(GameStateManager.new())
	# death_delay 设为极短，避免真实等待
	_manager.death_delay = 0.01
	# 手动触发 _ready 逻辑（因为是 auto_free，需模拟 _ready）
	_manager._ready()


## =========================================================================
## AC-1: 游戏启动初始化完成后，当前状态为 TITLE
## =========================================================================
func test_initial_state_is_title() -> void:
	assert_int(_manager.get_current_state()) \
		.is_equal(GameStateManager.State.TITLE)


## =========================================================================
## AC-2: TITLE→COMBAT 转换发出 state_changed(TITLE, COMBAT) 信号，返回 true
## =========================================================================
func test_title_to_combat_emits_signal() -> void:
	var signal_monitor := monitor_signals(_manager)
	var result: bool = _manager.change_state(GameStateManager.State.COMBAT)

	assert_bool(result).is_true()
	assert_int(_manager.get_current_state()) \
		.is_equal(GameStateManager.State.COMBAT)

	# 验证信号参数
	await assert_signal(signal_monitor).is_emitted("state_changed")


## =========================================================================
## AC-3: COMBAT→DEATH 转换发出 state_changed(COMBAT, DEATH) 信号
## =========================================================================
func test_combat_to_death_emits_signal() -> void:
	var signal_monitor := monitor_signals(_manager)

	# 先转到 COMBAT
	_manager.change_state(GameStateManager.State.COMBAT)
	# 再转到 DEATH
	var result: bool = _manager.change_state(GameStateManager.State.DEATH)

	assert_bool(result).is_true()
	assert_int(_manager.get_current_state()) \
		.is_equal(GameStateManager.State.DEATH)

	await assert_signal(signal_monitor).is_emitted("state_changed")


## =========================================================================
## AC-4: DEATH 状态下 death_delay 完成后 change_state(RESTART)
## 触发两次信号 (DEATH→RESTART, RESTART→COMBAT)，最终状态 COMBAT
## =========================================================================
func test_death_delay_then_restart_emits_two_signals() -> void:
	# 进入 DEATH
	_manager.change_state(GameStateManager.State.COMBAT)
	_manager.change_state(GameStateManager.State.DEATH)

	# 等待 death_delay 完成
	await get_tree().create_timer(_manager.death_delay + 0.05).timeout

	# 收集信号
	var received_signals: Array = []
	_manager.state_changed.connect(func(old_s: GameStateManager.State, new_s: GameStateManager.State) -> void:
		received_signals.append([old_s, new_s])
	)

	# 触发 RESTART
	var result: bool = _manager.change_state(GameStateManager.State.RESTART)

	assert_bool(result).is_true()
	assert_int(_manager.get_current_state()) \
		.is_equal(GameStateManager.State.COMBAT)

	# 验证两次信号
	assert_int(received_signals.size()).is_equal(2)
	# 第一次: DEATH→RESTART
	assert_int(received_signals[0][0]).is_equal(GameStateManager.State.DEATH)
	assert_int(received_signals[0][1]).is_equal(GameStateManager.State.RESTART)
	# 第二次: RESTART→COMBAT
	assert_int(received_signals[1][0]).is_equal(GameStateManager.State.RESTART)
	assert_int(received_signals[1][1]).is_equal(GameStateManager.State.COMBAT)


## =========================================================================
## AC-5: DEATH 状态下 death_delay 未完成时 change_state(RESTART)
## 返回 false，状态保持 DEATH，不发出信号
## =========================================================================
func test_death_delay_not_elapsed_restart_rejected() -> void:
	_manager.change_state(GameStateManager.State.COMBAT)
	_manager.change_state(GameStateManager.State.DEATH)

	# 不等待 delay，立即尝试 RESTART
	var received_signals: Array = []
	_manager.state_changed.connect(func(old_s: GameStateManager.State, new_s: GameStateManager.State) -> void:
		received_signals.append([old_s, new_s])
	)

	var result: bool = _manager.change_state(GameStateManager.State.RESTART)

	assert_bool(result).is_false()
	assert_int(_manager.get_current_state()) \
		.is_equal(GameStateManager.State.DEATH)
	assert_int(received_signals.size()).is_equal(0)


## =========================================================================
## AC-6: 同状态 change_state 无操作，返回 false，无信号
## =========================================================================
func test_same_state_returns_false_no_signal() -> void:
	var received_signals: Array = []
	_manager.state_changed.connect(func(old_s: GameStateManager.State, new_s: GameStateManager.State) -> void:
		received_signals.append([old_s, new_s])
	)

	var result: bool = _manager.change_state(GameStateManager.State.TITLE)

	assert_bool(result).is_false()
	assert_int(_manager.get_current_state()) \
		.is_equal(GameStateManager.State.TITLE)
	assert_int(received_signals.size()).is_equal(0)


## =========================================================================
## AC-7: 非法转换 (如 TITLE→DEATH) 返回 false，push_warning 输出
## =========================================================================
func test_invalid_transition_rejected_with_warning() -> void:
	var received_signals: Array = []
	_manager.state_changed.connect(func(old_s: GameStateManager.State, new_s: GameStateManager.State) -> void:
		received_signals.append([old_s, new_s])
	)

	# TITLE→DEATH 是非法转换
	var result: bool = _manager.change_state(GameStateManager.State.DEATH)

	assert_bool(result).is_false()
	assert_int(_manager.get_current_state()) \
		.is_equal(GameStateManager.State.TITLE)
	assert_int(received_signals.size()).is_equal(0)


## =========================================================================
## AC-8: 信号在同一帧内到达所有监听系统
## =========================================================================
func test_signal_arrives_same_frame() -> void:
	var listener_a_received: bool = false
	var listener_b_received: bool = false
	var listener_c_received: bool = false

	_manager.state_changed.connect(func(_old_s: GameStateManager.State, _new_s: GameStateManager.State) -> void:
		listener_a_received = true
	)
	_manager.state_changed.connect(func(_old_s: GameStateManager.State, _new_s: GameStateManager.State) -> void:
		listener_b_received = true
	)
	_manager.state_changed.connect(func(_old_s: GameStateManager.State, _new_s: GameStateManager.State) -> void:
		listener_c_received = true
	)

	# 触发状态转换
	_manager.change_state(GameStateManager.State.COMBAT)

	# 同一帧内所有监听器都应收到
	assert_bool(listener_a_received).is_true()
	assert_bool(listener_b_received).is_true()
	assert_bool(listener_c_received).is_true()


## =========================================================================
## AC-Edge: 死亡优先级覆盖测试
## 模拟同帧竞争：在 INTERMISSION 状态下，DEATH 转换应成功
## =========================================================================
func test_death_from_intermission_allowed() -> void:
	# 流程: TITLE→COMBAT→INTERMISSION→DEATH
	_manager.change_state(GameStateManager.State.COMBAT)
	_manager.change_state(GameStateManager.State.INTERMISSION)

	var result: bool = _manager.change_state(GameStateManager.State.DEATH)

	assert_bool(result).is_true()
	assert_int(_manager.get_current_state()) \
		.is_equal(GameStateManager.State.DEATH)


## =========================================================================
## 额外边界测试: 完整状态循环
## TITLE→COMBAT→DEATH→wait→RESTART→COMBAT→DEATH→wait→RESTART→COMBAT
## =========================================================================
func test_full_state_cycle() -> void:
	# TITLE→COMBAT
	assert_bool(_manager.change_state(GameStateManager.State.COMBAT)).is_true()
	assert_int(_manager.get_current_state()).is_equal(GameStateManager.State.COMBAT)

	# COMBAT→DEATH
	assert_bool(_manager.change_state(GameStateManager.State.DEATH)).is_true()
	assert_int(_manager.get_current_state()).is_equal(GameStateManager.State.DEATH)

	# 等待死亡延迟
	await get_tree().create_timer(_manager.death_delay + 0.05).timeout

	# DEATH→RESTART→COMBAT (自动)
	assert_bool(_manager.change_state(GameStateManager.State.RESTART)).is_true()
	assert_int(_manager.get_current_state()).is_equal(GameStateManager.State.COMBAT)

	# 第二次循环
	assert_bool(_manager.change_state(GameStateManager.State.DEATH)).is_true()
	await get_tree().create_timer(_manager.death_delay + 0.05).timeout
	assert_bool(_manager.change_state(GameStateManager.State.RESTART)).is_true()
	assert_int(_manager.get_current_state()).is_equal(GameStateManager.State.COMBAT)


## =========================================================================
## 额外边界测试: INTERMISSION 期间可以死亡
## =========================================================================
func test_combat_to_intermission_allowed() -> void:
	_manager.change_state(GameStateManager.State.COMBAT)
	var result: bool = _manager.change_state(GameStateManager.State.INTERMISSION)

	assert_bool(result).is_true()
	assert_int(_manager.get_current_state()) \
		.is_equal(GameStateManager.State.INTERMISSION)
